/**
 * context-builder.ts — 태스크 실행 프롬프트 빌드
 * scripts/lib/context-builder.sh의 Node.js 포팅
 */
import fs from "fs";
import path from "path";
import { parseFrontmatter, getString } from "./frontmatter-utils";
import { PROJECT_ROOT, TASKS_DIR, PACKAGE_DIR } from "./paths";
import { loadSettings } from "./settings";

// ── Template 렌더링 ────────────────────────────────────────

function resolveTemplate(tplPath: string): string {
  const orchestrationPath = path.join(
    PROJECT_ROOT,
    ".orchestration",
    "template",
    tplPath,
  );
  if (fs.existsSync(orchestrationPath)) return orchestrationPath;
  const packagePath = path.join(PACKAGE_DIR, "template", tplPath);
  if (fs.existsSync(packagePath)) return packagePath;
  throw new Error(`Template not found: ${tplPath}`);
}

function renderTemplate(tplPath: string, vars: Record<string, string>): string {
  const resolved = resolveTemplate(tplPath);
  let content = fs.readFileSync(resolved, "utf-8");
  for (const [key, value] of Object.entries(vars)) {
    content = content.replace(new RegExp(`\\{\\{${key}\\}\\}`, "g"), value);
  }
  return content;
}

// ── 완료된 태스크 목록 ─────────────────────────────────────

function getDoneTaskIds(repoRoot: string): string[] {
  const results: string[] = [];
  const dirs = [
    path.join(repoRoot, ".orchestration", "tasks"),
    path.join(repoRoot, "docs", "task"),
    path.join(repoRoot, "docs", "requests"),
  ];

  for (const dir of dirs) {
    if (!fs.existsSync(dir)) continue;
    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith(".md")) continue;
      if (!file.startsWith("TASK-") && !file.startsWith("REQ-")) continue;
      try {
        const raw = fs.readFileSync(path.join(dir, file), "utf-8");
        const { data } = parseFrontmatter(raw);
        if (getString(data, "status") === "done") {
          results.push(file);
        }
      } catch {
        /* ignore */
      }
    }
  }
  return results;
}

// ── .claudeignore 생성 ─────────────────────────────────────

export function setupContextFilter(
  worktreePath: string,
  repoRoot: string,
): void {
  if (!fs.existsSync(worktreePath)) return;

  const ignoreFile = path.join(worktreePath, ".claudeignore");
  const lines: string[] = [
    "# Auto-generated by context-builder.ts",
    "docs/task/archive/",
    "node_modules/",
    ".git/",
    "output/",
    "scripts/orchestrate.sh",
    "scripts/night-worker.sh",
    "scripts/run-pipeline.sh",
  ];

  // srcPaths 기반 필터
  const settings = loadSettings();
  const srcPaths = settings.srcPaths.map((s) => s.replace(/\/$/, ""));
  try {
    const entries = fs.readdirSync(worktreePath, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const name = entry.name;
      if (
        [
          ".git",
          ".orchestration",
          "node_modules",
          "output",
          "docs",
          "scripts",
          "template",
        ].includes(name)
      )
        continue;
      const inSrc = srcPaths.some(
        (sp) => name === sp || sp.startsWith(`${name}/`),
      );
      if (!inSrc) lines.push(`${name}/`);
    }
  } catch {
    /* ignore */
  }

  // 완료된 태스크 제외
  const doneFiles = getDoneTaskIds(repoRoot);
  if (doneFiles.length > 0) {
    lines.push("", "# 완료된 태스크");
    for (const f of doneFiles) {
      lines.push(`docs/task/${f}`);
      lines.push(`docs/requests/${f}`);
    }
  }

  try {
    fs.writeFileSync(ignoreFile, lines.join("\n") + "\n");
  } catch {
    /* ignore */
  }
}

// ── 레이어드 컨텍스트 빌드 ─────────────────────────────────

function resolveGlob(pattern: string, worktreePath: string): string[] {
  const results: string[] = [];

  if (pattern.includes("*")) {
    // glob 패턴 → 디렉토리 탐색
    const baseDir = pattern
      .replace(/\*\*.*/, "")
      .replace(/\*.*/, "")
      .replace(/\/$/, "");
    const searchDir = worktreePath ? path.join(worktreePath, baseDir) : baseDir;

    if (fs.existsSync(searchDir)) {
      collectFiles(searchDir, results, 0, 3);
    }
    return results.slice(0, 10);
  }

  // 일반 파일 경로
  const full = worktreePath ? path.join(worktreePath, pattern) : pattern;
  if (fs.existsSync(full)) results.push(full);
  return results;
}

function collectFiles(
  dir: string,
  results: string[],
  depth: number,
  maxDepth: number,
): void {
  if (depth > maxDepth || results.length >= 15) return;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (results.length >= 15) return;
      if (entry.name === "node_modules" || entry.name === ".git") continue;
      if (
        entry.name.includes(".test.") ||
        entry.name.includes(".spec.") ||
        entry.name.includes(".stories.")
      )
        continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        collectFiles(full, results, depth + 1, maxDepth);
      } else if (/\.(ts|tsx|js|jsx|sh)$/.test(entry.name)) {
        results.push(full);
      }
    }
  } catch {
    /* ignore */
  }
}

export function buildLayeredContext(
  scope: string[],
  worktreePath: string,
): string {
  if (scope.length === 0) return "";

  const allFiles: string[] = [];
  for (const pattern of scope) {
    if (!pattern.trim()) continue;
    const resolved = resolveGlob(pattern.trim(), worktreePath);
    allFiles.push(...resolved);
    if (allFiles.length >= 15) break;
  }

  const uniqueFiles = [...new Set(allFiles)].slice(0, 15);
  const parts: string[] = [];

  for (const realPath of uniqueFiles) {
    if (!fs.existsSync(realPath)) continue;

    // 표시용 상대 경로
    let displayPath = realPath;
    if (worktreePath) {
      displayPath = realPath.replace(worktreePath + "/", "");
    }

    let content: string;
    try {
      content = fs.readFileSync(realPath, "utf-8");
    } catch {
      continue;
    }
    const lines = content.split("\n").length;

    if (lines <= 300) {
      parts.push(
        `### ${displayPath} (${lines}줄)\n\`\`\`\n${content}\n\`\`\`\n`,
      );
    } else if (lines <= 800) {
      parts.push(
        `### ${displayPath} (${lines}줄 — 변경 최소화)\n\`\`\`\n${content}\n\`\`\`\n`,
      );
    } else {
      // signature만 추출
      const sigs = content
        .split("\n")
        .map((line, i) => ({ line, num: i + 1 }))
        .filter(({ line }) =>
          /^(export |import |function |class |interface |type |const |async |def )/.test(
            line,
          ),
        )
        .slice(0, 60)
        .map(({ line, num }) => `${num}: ${line}`)
        .join("\n");
      parts.push(
        `### ${displayPath} (${lines}줄 — 시그니처만, 필요 시 직접 읽어라)\n\`\`\`\n${sigs}\n\`\`\`\n`,
      );
    }
  }

  return parts.join("\n");
}

// ── 태스크 프롬프트 빌드 ───────────────────────────────────

export interface TaskPromptOptions {
  taskFile: string;
  taskFilename: string;
  scope: string[];
  context: string[];
  feedbackFile?: string;
  worktreePath: string;
}

export function buildTaskPrompt(opts: TaskPromptOptions): string {
  const taskContent = fs.existsSync(opts.taskFile)
    ? fs.readFileSync(opts.taskFile, "utf-8")
    : "";

  // scope 섹션
  let scopeSection = "";
  if (opts.scope.length > 0) {
    const scopeList = opts.scope.map((f) => `- ${f}`).join("\n");
    const layered = buildLayeredContext(opts.scope, opts.worktreePath);

    scopeSection = `
## 작업 범위 (수정할 파일)
아래 파일들을 수정해라:
${scopeList}

scope 외 파일은 수정하지 마라.

## 작업 대상 파일 내용
${layered}
`;
  }

  // context 섹션 (읽기 전용)
  if (opts.context.length > 0) {
    const contextList = opts.context.map((f) => `- ${f}`).join("\n");
    const contextContent = buildLayeredContext(opts.context, opts.worktreePath);

    scopeSection += `
## 참조 파일 (읽기 전용 — 수정 금지)
아래 파일들을 반드시 읽고 참조해라. 단, 수정하지 마라:
${contextList}

## 참조 파일 내용
${contextContent}
`;
  }

  // 피드백 섹션
  let feedbackSection = "";
  if (opts.feedbackFile && fs.existsSync(opts.feedbackFile)) {
    const feedback = fs.readFileSync(opts.feedbackFile, "utf-8");
    feedbackSection = `
## 이전 리뷰 피드백 (수정 요청)
아래는 이전 리뷰에서 받은 수정 요청이다. 반드시 이 피드백을 반영하여 작업해라:

${feedback}`;
  }

  return renderTemplate("prompt/worker-task.md", {
    scope_section: scopeSection,
    task_filename: opts.taskFilename,
    task_content: taskContent,
    feedback_section: feedbackSection,
  });
}

// ── 리뷰 프롬프트 빌드 ────────────────────────────────────

export interface ReviewPromptOptions {
  taskFile: string;
  taskFilename: string;
  baseBranch?: string;
}

export function buildReviewPrompt(opts: ReviewPromptOptions): string {
  const taskContent = fs.existsSync(opts.taskFile)
    ? fs.readFileSync(opts.taskFile, "utf-8")
    : "";
  const baseBranch = opts.baseBranch ?? loadSettings().baseBranch;

  return renderTemplate("prompt/worker-review.md", {
    base_branch: baseBranch,
    task_filename: opts.taskFilename,
    task_content: taskContent,
  });
}
