/**
 * context-builder.ts — 태스크 실행 프롬프트 빌드
 * scripts/lib/context-builder.sh의 Node.js 포팅
 */
import fs from "fs";
import path from "path";
import { DASHBOARD_DIR, PROJECT_ROOT, TEMPLATE_DIR } from "../../lib/config/paths";
import { loadSettings } from "../../lib/config/settings";
import type { TaskExecutionHints } from "../../lib/task-execution-hints";
import { getTasksByStatus } from "../../service/task-store";

// ── Template 렌더링 ────────────────────────────────────────

function resolveTemplate(tplPath: string): string {
  const orchestrationPath = path.join(TEMPLATE_DIR, tplPath);
  if (fs.existsSync(orchestrationPath)) return orchestrationPath;
  const localPath = path.join(DASHBOARD_DIR, "template", tplPath);
  if (fs.existsSync(localPath)) return localPath;
  throw new Error(`Template not found: ${tplPath}`);
}

function renderTemplate(tplPath: string, vars: Record<string, string>): string {
  const resolved = resolveTemplate(tplPath);
  let content = fs.readFileSync(resolved, "utf-8");
  for (const [key, value] of Object.entries(vars)) {
    content = content.replace(new RegExp(`\\{\\{${key}\\}\\}`, "g"), value);
  }
  return content;
}

// ── 완료된 태스크 목록 ─────────────────────────────────────

function getDoneTaskIds(): string[] {
  try {
    const rows = getTasksByStatus("done");
    return rows.map((r) => r.id);
  } catch {
    return [];
  }
}

// ── .claudeignore 생성 ─────────────────────────────────────

export function setupContextFilter(
  worktreePath: string,
  repoRoot: string,
): void {
  if (!fs.existsSync(worktreePath)) return;

  const ignoreFile = path.join(worktreePath, ".claudeignore");
  const lines: string[] = [
    "# Auto-generated by context-builder.ts",
    "docs/task/archive/",
    "node_modules/",
    ".git/",
    "output/",
    "scripts/",
  ];

  // srcPaths 기반 필터
  const settings = loadSettings();
  const srcPaths = settings.srcPaths.map((s) => s.replace(/\/$/, ""));
  try {
    const entries = fs.readdirSync(worktreePath, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const name = entry.name;
      if (
        [
          ".git",
          ".orchestration",
          "node_modules",
          "output",
          "docs",
          "scripts",
          "template",
        ].includes(name)
      )
        continue;
      const inSrc = srcPaths.some(
        (sp) => name === sp || sp.startsWith(`${name}/`),
      );
      if (!inSrc) lines.push(`${name}/`);
    }
  } catch {
    /* ignore */
  }

  // 완료된 태스크 제외
  const doneIds = getDoneTaskIds();
  if (doneIds.length > 0) {
    lines.push("", "# 완료된 태스크");
    for (const id of doneIds) {
      lines.push(`docs/task/${id}*.md`);
    }
  }

  try {
    fs.writeFileSync(ignoreFile, lines.join("\n") + "\n");
  } catch {
    /* ignore */
  }
}

// ── 레이어드 컨텍스트 빌드 ─────────────────────────────────

function resolveGlob(pattern: string, worktreePath: string): string[] {
  const results: string[] = [];

  if (pattern.includes("*")) {
    // glob 패턴 → 디렉토리 탐색
    const baseDir = pattern
      .replace(/\*\*.*/, "")
      .replace(/\*.*/, "")
      .replace(/\/$/, "");
    const searchDir = worktreePath ? path.join(worktreePath, baseDir) : baseDir;

    if (fs.existsSync(searchDir)) {
      collectFiles(searchDir, results, 0, 3);
    }
    return results.slice(0, 10);
  }

  // 일반 파일 경로
  const full = worktreePath ? path.join(worktreePath, pattern) : pattern;
  if (fs.existsSync(full)) results.push(full);
  return results;
}

function collectFiles(
  dir: string,
  results: string[],
  depth: number,
  maxDepth: number,
): void {
  if (depth > maxDepth || results.length >= 15) return;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (results.length >= 15) return;
      if (entry.name === "node_modules" || entry.name === ".git") continue;
      if (
        entry.name.includes(".test.") ||
        entry.name.includes(".spec.") ||
        entry.name.includes(".stories.")
      )
        continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        collectFiles(full, results, depth + 1, maxDepth);
      } else if (/\.(ts|tsx|js|jsx|sh)$/.test(entry.name)) {
        results.push(full);
      }
    }
  } catch {
    /* ignore */
  }
}

type ResolvedPattern = {
  pattern: string;
  hasWildcard: boolean;
  files: string[];
};

const DASHBOARD_GUIDE_SUMMARY = [
  "- OpenAI Assistants Playground 스타일의 단일 컬럼, 넉넉한 패딩/간격을 유지한다.",
  "- raw HTML `<input>/<select>/<textarea>` 대신 `@/components/ui/` 컴포넌트를 사용한다.",
  "- 페이지는 `<PageLayout>` + `<PageHeader>` 패턴, 섹션은 `space-y-4` 중심으로 구성한다.",
  "- 입력 요소가 이미 border를 가지므로 바깥 카드/이중 보더를 추가하지 않는다.",
  "- 같은 구조가 3회 이상 반복되면 컴포넌트로 추출하고, 새 UI 컴포넌트에는 `.stories.tsx`를 함께 둔다.",
].join("\n");

function resolvePatterns(
  patterns: string[],
  worktreePath: string,
): ResolvedPattern[] {
  return patterns
    .map((pattern) => pattern.trim())
    .filter((pattern) => pattern.length > 0)
    .map((pattern) => ({
      pattern,
      hasWildcard: pattern.includes("*"),
      files: resolveGlob(pattern, worktreePath),
    }));
}

function renderInjectedFile(realPath: string, worktreePath: string): string {
  if (!fs.existsSync(realPath)) return "";

  const displayPath = toDisplayPath(realPath, worktreePath);

  let content: string;
  try {
    content = fs.readFileSync(realPath, "utf-8");
  } catch {
    return "";
  }
  const lines = content.split("\n").length;

  if (lines <= 300) {
    return `### ${displayPath} (${lines}줄)\n\`\`\`\n${content}\n\`\`\`\n`;
  }
  if (lines <= 800) {
    return `### ${displayPath} (${lines}줄 — 변경 최소화)\n\`\`\`\n${content}\n\`\`\`\n`;
  }

  const sigs = content
    .split("\n")
    .map((line, i) => ({ line, num: i + 1 }))
    .filter(({ line }) =>
      /^(export |import |function |class |interface |type |const |async |def )/.test(
        line,
      ),
    )
    .slice(0, 60)
    .map(({ line, num }) => `${num}: ${line}`)
    .join("\n");
  return `### ${displayPath} (${lines}줄 — 시그니처만, 필요 시 직접 읽어라)\n\`\`\`\n${sigs}\n\`\`\`\n`;
}

export function buildLayeredContext(
  patterns: string[],
  worktreePath: string,
): string {
  if (patterns.length === 0) return "";

  const resolvedPatterns = resolvePatterns(patterns, worktreePath);
  const exactFiles = resolvedPatterns
    .filter((entry) => !entry.hasWildcard)
    .flatMap((entry) => entry.files);
  const uniqueExactFiles = [...new Set(exactFiles)].slice(0, 10);
  const parts: string[] = [];

  const wildcardEntries = resolvedPatterns.filter((entry) => entry.hasWildcard);
  if (wildcardEntries.length > 0) {
    const manifest = wildcardEntries
      .map((entry) => {
        const files = entry.files
          .slice(0, 8)
          .map((realPath) => toDisplayPath(realPath, worktreePath));
        if (files.length === 0) return `- ${entry.pattern} -> 일치 파일 없음`;
        const extra =
          entry.files.length > files.length
            ? ` 외 ${entry.files.length - files.length}개`
            : "";
        return `- ${entry.pattern} -> ${files.join(", ")}${extra}`;
      })
      .join("\n");
    parts.push(
      [
        "### 와일드카드 범위 요약",
        "아래 범위는 본문을 전부 주입하지 않았다. 먼저 이 목록을 신뢰하고 필요한 파일만 직접 읽어라.",
        manifest,
        "",
      ].join("\n"),
    );
  }

  for (const realPath of uniqueExactFiles) {
    const rendered = renderInjectedFile(realPath, worktreePath);
    if (rendered) parts.push(rendered);
  }

  return parts.join("\n");
}

function toDisplayPath(realPath: string, worktreePath: string): string {
  if (!worktreePath) return realPath;
  return realPath.replace(worktreePath + "/", "");
}

function summarizeResolvedPatterns(
  patterns: string[],
  worktreePath: string,
): string {
  const resolvedPatterns = resolvePatterns(patterns, worktreePath);
  if (resolvedPatterns.length === 0) return "";

  return resolvedPatterns
    .map(({ pattern, files }) => {
      const resolved = files
        .slice(0, 5)
        .map((realPath) => toDisplayPath(realPath, worktreePath));

      if (resolved.length === 0) {
        return `- ${pattern} -> 일치 파일 없음`;
      }

      return `- ${pattern} -> ${resolved.join(", ")}`;
    })
    .join("\n");
}

// ── 태스크 프롬프트 빌드 ───────────────────────────────────

export interface TaskPromptOptions {
  taskFile: string;
  taskFilename: string;
  scope: string[];
  context: string[];
  executionHints?: TaskExecutionHints | null;
  feedbackFile?: string;
  worktreePath: string;
}

export function buildTaskPrompt(opts: TaskPromptOptions): string {
  const taskContent = fs.existsSync(opts.taskFile)
    ? fs.readFileSync(opts.taskFile, "utf-8")
    : "";

  // scope 섹션
  let scopeSection = "";
  if (opts.scope.length > 0) {
    const scopeList = opts.scope.map((f) => `- ${f}`).join("\n");
    const layered = buildLayeredContext(opts.scope, opts.worktreePath);
    const resolvedScope = summarizeResolvedPatterns(opts.scope, opts.worktreePath);

    scopeSection = `
## 작업 범위 (수정할 파일)
아래 파일들을 수정해라:
${scopeList}

scope 외 파일은 수정하지 마라.

## scope 해석 결과
엔진이 미리 찾은 파일 목록이다. 먼저 이 목록과 아래 본문을 기준으로 작업해라:
${resolvedScope}

## 작업 대상 파일 내용
${layered}
`;
  }

  // context 섹션 (읽기 전용)
  if (opts.context.length > 0) {
    const contextList = opts.context.map((f) => `- ${f}`).join("\n");
    const contextContent = buildLayeredContext(opts.context, opts.worktreePath);
    const resolvedContext = summarizeResolvedPatterns(
      opts.context,
      opts.worktreePath,
    );

    scopeSection += `
## 참조 파일 (읽기 전용 — 수정 금지)
아래 파일들을 반드시 읽고 참조해라. 단, 수정하지 마라:
${contextList}

## context 해석 결과
엔진이 미리 찾은 참조 파일 목록이다. 추가 탐색 전에 먼저 이 목록을 확인해라:
${resolvedContext}

## 참조 파일 내용
${contextContent}
`;
  }

  if (opts.executionHints) {
    const { edit_files, read_only_files, do_not_explore } = opts.executionHints;
    const renderList = (items: string[]) =>
      items.length > 0 ? items.map((item) => `- ${item}`).join("\n") : "- (없음)";

    scopeSection += `
## 실행 힌트 (우선 경로)
아래 힌트는 scope를 대체하지 않는다. scope는 충돌/범위 경계이고, 이 섹션은 워커가 헤매지 않도록 주는 좁은 실행 안내다.

### edit_files
가능하면 아래 파일부터 바로 수정해라:
${renderList(edit_files)}

### read_only_files
아래 파일은 필요 시 읽기만 하고 수정하지 마라:
${renderList(read_only_files)}

### do_not_explore
아래 경로/패턴은 정말 필요한 근거가 생기기 전까지 탐색하지 마라:
${renderList(do_not_explore)}
`;
  }

  // 피드백 섹션
  let feedbackSection = "";
  if (opts.feedbackFile && fs.existsSync(opts.feedbackFile)) {
    const feedback = fs.readFileSync(opts.feedbackFile, "utf-8");
    feedbackSection = `
## 이전 리뷰 피드백 (수정 요청)
아래는 이전 리뷰에서 받은 수정 요청이다. 반드시 이 피드백을 반영하여 작업해라:

${feedback}`;
  }

  let optionalGuides = "";
  const scopeOrContextTouchesDashboard = [...opts.scope, ...opts.context].some(
    (p) => typeof p === "string" && p.includes("packages/dashboard"),
  );
  if (scopeOrContextTouchesDashboard) {
    try {
      resolveTemplate("prompt/dashboard-design-system.md");
      optionalGuides = `\n## packages/dashboard UI (엔진 주입)\nscope/context에 \`packages/dashboard\`가 포함되어 핵심 디자인 규칙만 요약 주입한다. 더 자세한 기준이 정말 필요할 때만 \`packages/dashboard/template/prompt/dashboard-design-system.md\`를 직접 열어라.\n\n${DASHBOARD_GUIDE_SUMMARY}\n`;
    } catch {
      optionalGuides = "";
    }
  }

  return renderTemplate("prompt/worker-task.md", {
    scope_section: scopeSection,
    task_filename: opts.taskFilename,
    task_content: taskContent,
    feedback_section: feedbackSection,
    optional_guides: optionalGuides,
  });
}

// ── 리뷰 프롬프트 빌드 ────────────────────────────────────

export interface ReviewPromptOptions {
  taskFile: string;
  taskFilename: string;
  baseBranch?: string;
}

export function buildReviewPrompt(opts: ReviewPromptOptions): string {
  const taskContent = fs.existsSync(opts.taskFile)
    ? fs.readFileSync(opts.taskFile, "utf-8")
    : "";
  const baseBranch = opts.baseBranch ?? loadSettings().baseBranch;

  return renderTemplate("prompt/worker-review.md", {
    base_branch: baseBranch,
    task_filename: opts.taskFilename,
    task_content: taskContent,
  });
}
