#!/bin/bash
# context-builder.sh — 태스크 실행에 필요한 최소 컨텍스트만 빌드
# 완료된 태스크/요청 파일을 제외하고 해당 태스크에 직접 관련된 파일만 포함

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# ── 완료된 태스크 ID 목록 반환 ───────────────────────────
# 용도: 완료된 태스크를 컨텍스트에서 제외
get_done_task_ids() {
  local repo_root="$1"
  local task_dir
  if [ -d "$repo_root/.orchestration/tasks" ]; then
    task_dir="$repo_root/.orchestration/tasks"
  else
    task_dir="$repo_root/docs/task"
  fi
  local req_dir="$repo_root/docs/requests"

  for dir in "$task_dir" "$req_dir"; do
    [ ! -d "$dir" ] && continue
    find "$dir" -maxdepth 1 \( -name "TASK-*.md" -o -name "REQ-*.md" \) 2>/dev/null | while read -r f; do
      local st 2>/dev/null || true
      st=$(get_field "$f" "status")
      if [ "$st" = "done" ]; then
        basename "$f"
      fi
    done
  done
}

# ── 태스크 파일 내용을 읽어 프롬프트에 임베드 ──────────────
# 인자: task_file_path
# 출력: 태스크 파일 전체 내용 (Claude가 별도로 읽을 필요 없음)
embed_task_content() {
  local task_file="$1"
  if [ ! -f "$task_file" ]; then
    echo ""
    return
  fi
  cat "$task_file"
}

# ── 워크트리에서 완료된 태스크 파일 숨기기 ──────────────────
# .claudeignore 파일을 생성하여 불필요한 파일을 Claude 컨텍스트에서 제외
# 인자: worktree_path, repo_root
setup_context_filter() {
  local worktree_path="$1"
  local repo_root="$2"
  local ignore_file="$worktree_path/.claudeignore"

  # 기본 제외 패턴
  cat > "$ignore_file" <<'IGNORE'
# Auto-generated by context-builder.sh — 컨텍스트 최소화
# 완료된 태스크 파일 제외
docs/task/archive/
# 불필요한 대형 디렉토리
node_modules/
.git/
output/
scripts/orchestrate.sh
scripts/night-worker.sh
scripts/run-pipeline.sh
IGNORE

  # 완료된 태스크 파일들을 개별 제외
  local done_files
  done_files=$(get_done_task_ids "$repo_root")
  if [ -n "$done_files" ]; then
    echo "" >> "$ignore_file"
    echo "# 완료된 태스크 (자동 생성)" >> "$ignore_file"
    while IFS= read -r fname; do
      [ -z "$fname" ] && continue
      echo "docs/task/${fname}" >> "$ignore_file"
      echo "docs/requests/${fname}" >> "$ignore_file"
    done <<< "$done_files"
  fi
}

# ── 최소 프롬프트 빌드 ────────────────────────────────────
# 태스크 파일 내용을 직접 임베드하여 Claude가 별도 파일 읽기를 최소화
# 인자: task_file, task_filename, scope, feedback_file(optional)
# 출력: 완성된 프롬프트 문자열
build_task_prompt() {
  local task_file="$1"
  local task_filename="$2"
  local scope="$3"
  local feedback_file="${4:-}"
  local context="${5:-}"

  local task_content
  task_content=$(embed_task_content "$task_file")

  # scope 섹션 빌드 (수정할 파일)
  local scope_section=""
  if [ -n "$scope" ]; then
    local scope_list=""
    while IFS= read -r f; do
      [ -n "$f" ] && scope_list="${scope_list}
- ${f}"
    done <<< "$scope"
    local layered_content
    layered_content=$(build_layered_context "$scope")
    scope_section="
## 작업 범위 (수정할 파일)
아래 파일들을 수정해라:${scope_list}

scope 외 파일은 수정하지 마라.

## 작업 대상 파일 내용
${layered_content}
"
  fi

  # context 섹션 빌드 (참조할 파일 — 읽기 전용)
  if [ -n "$context" ]; then
    local context_list=""
    while IFS= read -r f; do
      [ -n "$f" ] && context_list="${context_list}
- ${f}"
    done <<< "$context"
    local context_content
    context_content=$(build_layered_context "$context")
    scope_section="${scope_section}
## 참조 파일 (읽기 전용 — 수정 금지)
아래 파일들을 반드시 읽고 참조해라. 단, 수정하지 마라:${context_list}

## 참조 파일 내용
${context_content}
"
  fi

  # 피드백 섹션
  local feedback_section=""
  if [ -n "$feedback_file" ] && [ -f "$feedback_file" ]; then
    local feedback
    feedback=$(cat "$feedback_file")
    feedback_section="
## 이전 리뷰 피드백 (수정 요청)
아래는 이전 리뷰에서 받은 수정 요청이다. 반드시 이 피드백을 반영하여 작업해라:

${feedback}"
  fi

  render_template "prompt/worker-task.md" \
    "scope_section=${scope_section}" \
    "task_filename=${task_filename}" \
    "task_content=${task_content}" \
    "feedback_section=${feedback_section}"
}

# ── 계층형 context 빌드 (scope 파일 크기별 분류) ─────────
# 작은 파일(≤300줄): 전체 임베드
# 중간 파일(301-800줄): 전체 임베드 + 경고
# 큰 파일(>800줄): signature + type 정의만, Claude가 직접 읽기
build_layered_context() {
  local scope="$1"
  local worktree_path="${2:-}"
  local result=""

  [ -z "$scope" ] && return

  # scope의 glob 패턴을 실제 파일로 resolve
  local resolved_files=""
  while IFS= read -r pattern; do
    [ -z "$pattern" ] && continue

    # glob 패턴(** 포함)이면 find로 resolve
    if echo "$pattern" | grep -q '\*'; then
      local search_dir=""
      local base_dir
      base_dir=$(echo "$pattern" | sed 's/\*\*.*//;s/\*.*//;s|/$||')

      if [ -n "$worktree_path" ] && [ -d "$worktree_path/$base_dir" ]; then
        search_dir="$worktree_path/$base_dir"
      elif [ -d "$base_dir" ]; then
        search_dir="$base_dir"
      fi

      if [ -n "$search_dir" ]; then
        local found
        found=$(find "$search_dir" -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.sh" \) 2>/dev/null | grep -v node_modules | grep -v ".test." | grep -v ".spec." | grep -v ".stories." | sort | head -10)
        if [ -n "$found" ]; then
          resolved_files="${resolved_files}
${found}"
        fi
      fi
      continue
    fi

    # 일반 파일 경로
    if [ -n "$worktree_path" ] && [ -f "$worktree_path/$pattern" ]; then
      resolved_files="${resolved_files}
$worktree_path/$pattern"
    elif [ -f "$pattern" ]; then
      resolved_files="${resolved_files}
$pattern"
    fi
  done <<< "$scope"

  resolved_files=$(echo "$resolved_files" | sed '/^$/d' | head -15)

  [ -z "$resolved_files" ] && return

  while IFS= read -r real_path; do
    [ -z "$real_path" ] && continue

    # 표시용 상대 경로
    local f="$real_path"
    if [ -n "$worktree_path" ]; then
      f=$(echo "$real_path" | sed "s|^${worktree_path}/||")
    fi

    local lines
    lines=$(wc -l < "$real_path" | tr -d ' ')

    if [ "$lines" -le 300 ]; then
      # Layer 2: 전체 임베드
      result="${result}
### ${f} (${lines}줄)
\`\`\`
$(cat "$real_path")
\`\`\`

"
    elif [ "$lines" -le 800 ]; then
      # Layer 2+: 전체 임베드 + 경고
      result="${result}
### ${f} (${lines}줄 — 변경 최소화)
\`\`\`
$(cat "$real_path")
\`\`\`

"
    else
      # Layer 1: signature + type 정의만
      result="${result}
### ${f} (${lines}줄 — 시그니처만, 필요 시 직접 읽어라)
\`\`\`
$(grep -n -E '^(export |import |function |class |interface |type |const |async |def )' "$real_path" 2>/dev/null | head -60)
\`\`\`

"
    fi
  done <<< "$scope"

  echo "$result"
}

# ── 리뷰 프롬프트 빌드 ──────────────────────────────────
# 인자: task_file, task_filename, base_branch(optional, 기본값: main)
build_review_prompt() {
  local task_file="$1"
  local task_filename="$2"
  local base_branch="${3:-${BASE_BRANCH:-main}}"

  local task_content
  task_content=$(embed_task_content "$task_file")

  render_template "prompt/worker-review.md" \
    "base_branch=${base_branch}" \
    "task_filename=${task_filename}" \
    "task_content=${task_content}"
}
