#!/bin/bash
# context-builder.sh — 태스크 실행에 필요한 최소 컨텍스트만 빌드
# 완료된 태스크/요청 파일을 제외하고 해당 태스크에 직접 관련된 파일만 포함

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# ── 완료된 태스크 ID 목록 반환 ───────────────────────────
# 용도: 완료된 태스크를 컨텍스트에서 제외
get_done_task_ids() {
  local repo_root="$1"
  local task_dir="$repo_root/docs/task"
  local req_dir="$repo_root/docs/requests"

  for dir in "$task_dir" "$req_dir"; do
    [ ! -d "$dir" ] && continue
    find "$dir" -maxdepth 1 \( -name "TASK-*.md" -o -name "REQ-*.md" \) 2>/dev/null | while read -r f; do
      local st 2>/dev/null || true
      st=$(get_field "$f" "status")
      if [ "$st" = "done" ]; then
        basename "$f"
      fi
    done
  done
}

# ── 태스크 파일 내용을 읽어 프롬프트에 임베드 ──────────────
# 인자: task_file_path
# 출력: 태스크 파일 전체 내용 (Claude가 별도로 읽을 필요 없음)
embed_task_content() {
  local task_file="$1"
  if [ ! -f "$task_file" ]; then
    echo ""
    return
  fi
  cat "$task_file"
}

# ── 워크트리에서 완료된 태스크 파일 숨기기 ──────────────────
# .claudeignore 파일을 생성하여 불필요한 파일을 Claude 컨텍스트에서 제외
# 인자: worktree_path, repo_root
setup_context_filter() {
  local worktree_path="$1"
  local repo_root="$2"
  local ignore_file="$worktree_path/.claudeignore"

  # 기본 제외 패턴
  cat > "$ignore_file" <<'IGNORE'
# Auto-generated by context-builder.sh — 컨텍스트 최소화
# 완료된 태스크 파일 제외
docs/task/archive/
# 불필요한 대형 디렉토리
node_modules/
.git/
output/
IGNORE

  # 완료된 태스크 파일들을 개별 제외
  local done_files
  done_files=$(get_done_task_ids "$repo_root")
  if [ -n "$done_files" ]; then
    echo "" >> "$ignore_file"
    echo "# 완료된 태스크 (자동 생성)" >> "$ignore_file"
    while IFS= read -r fname; do
      [ -z "$fname" ] && continue
      echo "docs/task/${fname}" >> "$ignore_file"
      echo "docs/requests/${fname}" >> "$ignore_file"
    done <<< "$done_files"
  fi
}

# ── 최소 프롬프트 빌드 ────────────────────────────────────
# 태스크 파일 내용을 직접 임베드하여 Claude가 별도 파일 읽기를 최소화
# 인자: task_file, task_filename, scope, feedback_file(optional)
# 출력: 완성된 프롬프트 문자열
build_task_prompt() {
  local task_file="$1"
  local task_filename="$2"
  local scope="$3"
  local feedback_file="${4:-}"

  local task_content
  task_content=$(embed_task_content "$task_file")

  # scope 섹션 빌드
  local scope_section=""
  if [ -n "$scope" ]; then
    local scope_list=""
    while IFS= read -r f; do
      [ -n "$f" ] && scope_list="${scope_list}
- ${f}"
    done <<< "$scope"
    scope_section="
## 작업 범위 가이드
아래 파일들을 우선적으로 확인하고 이 범위 안에서 작업을 완료해라:${scope_list}

이 범위만으로 완료 조건을 충족할 수 없다고 판단되면, 범위 밖 파일도 자유롭게 수정해도 된다.
단, 범위 밖 작업은 최소한으로 하고 완료 조건 충족에 필요한 경우에만 해라.
"
  fi

  # 피드백 섹션
  local feedback_section=""
  if [ -n "$feedback_file" ] && [ -f "$feedback_file" ]; then
    local feedback
    feedback=$(cat "$feedback_file")
    feedback_section="
## 이전 리뷰 피드백 (수정 요청)
아래는 이전 리뷰에서 받은 수정 요청이다. 반드시 이 피드백을 반영하여 작업해라:

${feedback}"
  fi

  cat <<PROMPT
## 작업 규칙
- 이 Worktree 안에서만 코드를 수정한다
- main 브랜치를 직접 수정하지 않는다
- Task 상태를 완료 처리하지 않는다
- 작업이 끝나면 변경사항을 커밋해라
${scope_section}
## Task 정의 (${task_filename})
아래는 수행할 Task의 전체 내용이다. 완료 조건을 모두 충족하도록 작업해라.

\`\`\`markdown
${task_content}
\`\`\`
${feedback_section}
PROMPT
}

# ── 리뷰 프롬프트 빌드 ──────────────────────────────────
# 인자: task_file, task_filename, base_branch(optional, 기본값: main)
build_review_prompt() {
  local task_file="$1"
  local task_filename="$2"
  local base_branch="${3:-${BASE_BRANCH:-main}}"

  local task_content
  task_content=$(embed_task_content "$task_file")

  cat <<PROMPT
## 리뷰 규칙
- 코드를 직접 수정하지 않는다
- Task 파일의 완료 조건을 기준으로 검증한다
- git diff ${base_branch}에 나온 파일만 검증하라. 관련 없는 코드를 읽지 마라
- 불필요한 파일 탐색을 하지 마라. 간결하게 리뷰하고 결론을 빠르게 내라

## Task 정의 (${task_filename})
\`\`\`markdown
${task_content}
\`\`\`

다음 순서로 리뷰를 수행해라:

1. 위 Task의 완료 조건을 확인해라
2. 이 브랜치에서 변경된 코드를 git diff ${base_branch} 으로 확인해라
3. 완료 조건을 하나씩 검증해라
4. 테스트가 있으면 실행해서 통과 여부를 확인해라

리뷰 결과를 다음 형식으로 출력해라:

## 리뷰 결과: [승인 / 수정요청]

### 완료 조건 체크
- [ ] 또는 [x] 각 완료 조건 항목

### 발견된 문제 (있을 경우)
- 문제 설명

### 총평
- 한줄 요약
PROMPT
}
